create extension if not exists pgcrypto;

create table if not exists public.products (
  id bigint generated by default as identity primary key,
  external_id integer unique not null,
  slug text unique not null,
  name text not null,
  brand text not null,
  category text not null,
  price_ngn bigint not null check (price_ngn >= 0),
  stock integer not null default 0 check (stock >= 0),
  active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.orders (
  id uuid primary key default gen_random_uuid(),
  reference text unique not null,
  email text not null,
  customer_name text not null,
  phone text not null,
  delivery_address text not null,
  city text not null,
  state text not null,
  subtotal_ngn bigint not null check (subtotal_ngn >= 0),
  delivery_fee_ngn bigint not null default 0 check (delivery_fee_ngn >= 0),
  total_ngn bigint not null check (total_ngn >= 0),
  status text not null default 'pending',
  payment_status text not null default 'pending',
  paystack_transaction_id bigint,
  paid_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.order_items (
  id bigint generated by default as identity primary key,
  order_id uuid not null references public.orders(id) on delete cascade,
  external_product_id integer not null,
  product_name text not null,
  unit_price_ngn bigint not null check (unit_price_ngn >= 0),
  quantity integer not null check (quantity > 0),
  line_total_ngn bigint not null check (line_total_ngn >= 0)
);

create table if not exists public.inventory_movements (
  id bigint generated by default as identity primary key,
  external_product_id integer not null,
  order_id uuid references public.orders(id) on delete set null,
  quantity_delta integer not null,
  reason text not null,
  created_at timestamptz not null default now()
);

alter table public.products enable row level security;
alter table public.orders enable row level security;
alter table public.order_items enable row level security;
alter table public.inventory_movements enable row level security;

drop policy if exists "Public can read active products" on public.products;
create policy "Public can read active products"
on public.products for select
to anon, authenticated
using (active = true);

create index if not exists orders_reference_idx on public.orders(reference);
create index if not exists orders_email_idx on public.orders(email);
create index if not exists order_items_order_id_idx on public.order_items(order_id);
